language: python
env:
    global:
        - ENCRYPTION_LABEL: "56bf8f63e969"
        - COMMIT_AUTHOR_EMAIL: "philipp.sommer@unil.ch"
matrix:
    include:
        - python: 2.7
          env: BUILD_DOCS=true
        - python: 3.5
          env: BUILD_DOCS=false
services:
    - postgresql
addons:  # install gfortran
  apt:
    packages:
    - gfortran
install:
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    # set build_docs to the real value
    - if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "master" -o "$BUILD_DOCS" != "true" ]; then
          BUILD_DOCS="false";
      else
          BUILD_DOCS="true";
      fi
    # make sure we use an 'innocent' default matplotlib environment
    - touch matplotlibrc
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - pip install pyyaml  # is somehow not included in the current conda installation
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda create -n test python="$TRAVIS_PYTHON_VERSION" dask seaborn scipy numpy statsmodels matplotlib xarray
    - source activate test
    - conda install -c conda-forge cartopy
    - pip install model-organization
    - pip install coveralls pytest
    # use latest development version
    # NOTE: Remove this when psyplot is stable enough
    - git clone "https://github.com/Chilipp/psyplot.git" -b dev
    - cd psyplot && python setup.py install && cd .. && rm -rf psyplot
    - python setup.py install
    # install necessary module for the documentation and clone the existing
    # gh-pages for this repo into the *deploy* folder and clear everything
    - if [[ "$BUILD_DOCS" == "true" ]]; then
          pip install sphinx-fortran sphinx==1.3.5 sphinx_rtd_theme ipython sphinx-argparse autodocsumm;
          git clone $REPO deploy;
          cd deploy;
          git checkout "gh-pages" || git checkout --orphan "gh-pages";
          ls -ad  | grep -v ".git$" | grep -v ".$" | grep -v "..$" | xargs rm -r;
          touch .nojekyll
          cd ..;
      fi
    # export the environment for debugging
    - conda env export -n test

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script:
    - py.test -xvk DailyGHCN
    - if [[ "$BUILD_DOCS" == "true" ]]; then
          sphinx-build docs deploy;
      fi
    #- coverage run --source=gwgen setup.py test -a "-v -m 'not fullrun'"

after_success:
    - coveralls
    - if [[ "$BUILD_DOCS" == "true" ]]; then
          ./deploy.sh;
      fi
