name: gwgen-docs
channels:
    - chilipp
dependencies:
    - gcc
    - matplotlib
    - numpy
    - sphinx
    - seaborn
    - ipython
    - scipy
    - jupyter_client
    - psyplot
    - pip:
        - autodocsumm
        - sphinx-argparse
        - sphinxfortran
        - model-organization
